// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfOnY-TmhR7v5o8JiLOoUmcWgBEIU2fk',
    appId: '1:451101327078:web:3053243db23fe009e74527',
    messagingSenderId: '451101327078',
    projectId: 'ecommerce-4fc77',
    authDomain: 'ecommerce-4fc77.firebaseapp.com',
    storageBucket: 'ecommerce-4fc77.appspot.com',
    measurementId: 'G-506C72LKCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaK1QEHky4cnvq9Ra-U4IO7gJSMv8ym9U',
    appId: '1:451101327078:android:1db4d99e286fd6ace74527',
    messagingSenderId: '451101327078',
    projectId: 'ecommerce-4fc77',
    storageBucket: 'ecommerce-4fc77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsPrBduM9BcFHugUOPl8Z2ikSXRleLDCg',
    appId: '1:451101327078:ios:a150930c170f6156e74527',
    messagingSenderId: '451101327078',
    projectId: 'ecommerce-4fc77',
    storageBucket: 'ecommerce-4fc77.appspot.com',
    iosClientId: '451101327078-ekc4q73sgmucep7bdo86i27dq67t4ao1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommeraceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsPrBduM9BcFHugUOPl8Z2ikSXRleLDCg',
    appId: '1:451101327078:ios:2ba7e5b2796ebc01e74527',
    messagingSenderId: '451101327078',
    projectId: 'ecommerce-4fc77',
    storageBucket: 'ecommerce-4fc77.appspot.com',
    iosClientId: '451101327078-7t19ld7a425j82lhnpab82h5no0h455e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommeraceapp.RunnerTests',
  );
}
